// This file is automatically generated.
// Please do not change this file!

/* tslint:disable */
/* eslint-disable */

interface CssExports {
  'description': string;
  'info': string;
  'likes': string;
  'modalContainer': string;
  'modalHeader': string;
  'post': string;
  'postAccountImage': string;
  'postContent': string;
  'postPubliImage': string;
  'postThumbnail': string;
  'postTime': string;
  'profilePic': string;
  'user': string;
  'username': string;
}
const cssExports: CssExports;
export default cssExports;
