// This file is automatically generated.
// Please do not change this file!

/* tslint:disable */
/* eslint-disable */

interface CssExports {
  'boutonLiens': string;
  'contactIcon': string;
  'content': string;
  'etatBar': string;
  'faceBookAccount': string;
  'liens': string;
  'links': string;
  'message': string;
  'post': string;
  'profile': string;
  'teams': string;
  'timestamp': string;
  'usernameStory': string;
  'welcome': string;
  'welcomeImage': string;
}
const cssExports: CssExports;
export default cssExports;
