// This file is automatically generated.
// Please do not change this file!

/* tslint:disable */
/* eslint-disable */

interface CssExports {
  'ProfileDescription': string;
  'borderFlexStyle': string;
  'compteurs': string;
  'container': string;
  'gapBetweenProfile': string;
  'playIcon': string;
  'post': string;
  'postImage': string;
  'postThumbnail': string;
  'profilePic': string;
  'stats': string;
  'username': string;
}
const cssExports: CssExports;
export default cssExports;
